# Generated by Django 5.1 on 2025-09-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_review_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
