# Generated by Django 5.1 on 2025-09-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='heart',
            field=models.BooleanField(default=False),
        ),
    ]
